//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schillings.SwordPhish.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schillings.SwordPhish.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] email {
            get {
                object obj = ResourceManager.GetObject("email", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr style=&apos;mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes&apos;&gt;
        ///  &lt;td width=188 valign=top style=&apos;width:141.35pt;border:solid windowtext 1.0pt;
        ///  mso-border-alt:solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;tab-stops:146.25pt&apos;&gt;{0}&lt;o:p&gt;&lt;/o:p&gt;&lt;/p&gt;
        ///  &lt;/td&gt;
        ///  &lt;td width=652 valign=top style=&apos;width:489.05pt;border:solid windowtext 1.0pt;
        ///  border-left:none;mso-border-left-alt:solid windowtext .5pt;mso-border-alt:
        ///  solid windowtext .5pt;padding:0cm 5.4pt 0cm 5.4pt&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EmailHeaderTableRowHtml {
            get {
                return ResourceManager.GetString("EmailHeaderTableRowHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect.
        /// </summary>
        public static string GroupLabel {
            get {
                return ResourceManager.GetString("GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap high_importance {
            get {
                object obj = ResourceManager.GetObject("high_importance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Priority.
        /// </summary>
        public static string HighPriority {
            get {
                return ResourceManager.GetString("HighPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_reported {
            get {
                object obj = ResourceManager.GetObject("icon_reported", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap low_importance {
            get {
                object obj = ResourceManager.GetObject("low_importance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Priority.
        /// </summary>
        public static string LowPriority {
            get {
                return ResourceManager.GetString("LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report as Phishing.
        /// </summary>
        public static string ReportButton {
            get {
                return ResourceManager.GetString("ReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report this e-mail as suspicious and a suspected phishing attempt..
        /// </summary>
        public static string ReportButtonHelp {
            get {
                return ResourceManager.GetString("ReportButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        public static string Reported {
            get {
                return ResourceManager.GetString("Reported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reported this e-mail on {0} - thank you..
        /// </summary>
        public static string ReportedDate {
            get {
                return ResourceManager.GetString("ReportedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SwordPhish.
        /// </summary>
        public static string SwordPhish {
            get {
                return ResourceManager.GetString("SwordPhish", resourceCulture);
            }
        }
    }
}
